# Generated by Django 5.1.3 on 2024-12-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('gid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=52)),
                ('password', models.CharField(max_length=52)),
                ('is_lock', models.SmallIntegerField(default=0)),
                ('created_id', models.BigIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_id', models.BigIntegerField(blank=True, default=1)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('gid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('created_id', models.BigIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_id', models.BigIntegerField(blank=True, default=1)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
